spring.application.name=crawler

spring.cloud.vault.token=${VAULT_TOKEN}
spring.cloud.vault.scheme=http
spring.cloud.vault.kv.enabled=true
spring.config.import=vault://
spring.cloud.vault.generic.enabled=false

datasource.url=jdbc:postgresql://localhost:5432/crawler

spring.kafka.bootstrap-servers=localhost:19092,localhost:19093,localhost:19094

arxiv.url=https://oaipmh.arxiv.org/oai

# Disable Hibernate DDL automatic changes
spring.jpa.hibernate.ddl-auto=none

# Liquibase Configuration
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml