spring.application.name=recommendation

spring.ai.openai.base-url=https://ai.api.cloud.yandex.net/v1
spring.ai.openai.api-key=${PROVIDER_API_KEY}
spring.ai.openai.chat.options.model=qwen3.6-35b-a3b/latest
spring.ai.openai.chat.temperature=0.3
yandex.ai.model.folder=b1gkb2ahd5d9q96i549s

arxiv.api.url=https://arxiv.org

#spring.kafka.bootstrap-servers=localhost:9093

spring.datasource.url=jdbc:postgresql://localhost:5432/recommendations
spring.datasource.username=admin
spring.datasource.password=mysecretpassword

# Disable Hibernate DDL automatic changes
spring.jpa.hibernate.ddl-auto=none

# Liquibase Configuration
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml