spring.application.name=recommendation

spring.cloud.vault.token=${VAULT_TOKEN}
spring.cloud.vault.scheme=http
spring.cloud.vault.kv.enabled=true
spring.config.import=vault://
spring.cloud.vault.generic.enabled=false

spring.ai.openai.base-url=https://ai.api.cloud.yandex.net/v1
spring.ai.openai.chat.model=qwen3.6-35b-a3b/latest
spring.ai.openai.chat.temperature=0.1

spring.kafka.bootstrap-servers=localhost:19092,localhost:19093,localhost:19094

datasource.url=jdbc:postgresql://localhost:5432/recommendations

# Disable Hibernate DDL automatic changes
spring.jpa.hibernate.ddl-auto=none

# Liquibase Configuration
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

management.tracing.sampling.probability=0.1