services:
  postgres:
    container_name: "common-db"
    hostname: pghost
    image: postgres:17
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_MULTIPLE_DATABASES: configurator, communicator, crawler, recommendations
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
      - ./postgres-init-multiple-dbs.sh:/docker-entrypoint-initdb.d/init-multiple-dbs.sh
    networks:
      - shared
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true

  kafka1:
    image: apache/kafka:4.3.1
    container_name: kafka-single
    hostname: kfkhost
    environment:
      CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kfkhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka1:9093
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - /var/lib/kafka/data
    networks:
      - shared
    ports:
      - 9092:9092

  recommendations:
    image: yahoondex/archhelper-recommendations:latest
    container_name: recommendations
    depends_on:
      - postgres
      - kafka1
    environment:
      VAULTHOST: vaulthost
      VAULT_TOKEN: ${VAULT_TOKEN}
      PGHOST: pghost
      KFKHOST: kfkhost
      OTEL: grafana
    networks:
      - shared

  crawler:
    image: yahoondex/archhelper-crawler:latest
    container_name: crawler
    depends_on:
      - postgres
      - kafka1
    environment:
      VAULTHOST: vaulthost
      VAULT_TOKEN: ${VAULT_TOKEN}
      PGHOST: pghost
      KFKHOST: kfkhost
      OTEL: grafana
    networks:
      - shared

  configurator:
    image: yahoondex/archhelper-configurator:latest
    container_name: configurator
    depends_on:
      - postgres
      - kafka1
    environment:
      VAULTHOST: vaulthost
      VAULT_TOKEN: ${VAULT_TOKEN}
      PGHOST: pghost
      KFKHOST: kfkhost
      KEYCLOAK: keycloak
      KCKPORT: 8080
      OTEL: grafana
    ports:
      - 8080:8080
    networks:
      - shared

  communicator:
    image: yahoondex/archhelper-communicator:latest
    container_name: communicator
    depends_on:
      - postgres
      - kafka1
    environment:
      VAULTHOST: vaulthost
      VAULT_TOKEN: ${VAULT_TOKEN}
      PGHOST: pghost
      KFKHOST: kfkhost
      OTEL: grafana
    networks:
      - shared

volumes:
  pgdata:
    driver: local

networks:
  shared:
    name: shared
    driver: bridge
    external: true