spring.application.name=configurator
server.port=8080

spring.cloud.vault.token=${VAULT_TOKEN}
spring.cloud.vault.scheme=http
spring.cloud.vault.kv.enabled=true
spring.config.import=vault://
spring.cloud.vault.generic.enabled=false

#spring.kafka.bootstrap-servers=localhost:19092,localhost:19093,localhost:19094
spring.kafka.bootstrap-servers=localhost:9092

datasource.url=jdbc:postgresql://localhost:5432/configurator

# Disable Hibernate DDL automatic changes
spring.jpa.hibernate.ddl-auto=none

# Liquibase Configuration
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/yahoonex-arch-helper
#spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:9090/realms/yahoonex-arch-helper
#spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username
#spring.security.oauth2.client.registration.keycloak.scope=openid
#spring.security.oauth2.client.registration.keycloak.client-id=arch-helper-client-id
#spring.security.oauth2.client.registration.keycloak.client-secret=${configurator.clientSecret}